
%------Frekvensen----
f = 2450e6;
o = 2*pi*f;
scale = 70e9;
%------Materialets parametrar
u0=4*pi*1e-7;
gamma = 1.759e11;
H_0 = 10000/(4*pi);
M_S = 1800/(4*pi);

w_0 = gamma*H_0;
w_m = gamma*M_S;

%w_0 = 12e9*2*pi;
%w_m = 7.04e9*2*pi;

e = 15;
u = u0*(1+w_0*w_m/(w_0^2-o^2));
k = u0*o*w_m/(w_0^2-o^2);

%------Vågtal--------
b = o*sqrt(e*(u+k));   % beta pozitiv
bb = o*sqrt(e*(u-k));  % beta negativ

k = 2*pi/(3e8/f);
n = 377;
d = 2e-5;
y=e*o/b;
yy=e*o/bb;

% R1=([-1/2*(2*n^3*yy^2*exp(-i*bb*d)*exp(-i*b*d)*y^2-2*n^3*...
%     yy^2*exp(-i*bb*d)*exp(i*b*d)*y^2+2*n^3*yy*exp(-i*bb*d)*y^3*exp(-i*b*d)...
%     +4*yy^2*exp(i*bb*d)*n^3*exp(i*b*d)*y^2-4*yy^2*exp(i*bb*d)*n^3*exp(-i*b*d)...
%     *y^2-2*yy*exp(-i*bb*d)*n^3*exp(i*b*d)*y^3+2*exp(-i*bb*d)*yy*exp(i*bb*d)*n^2*y^2-2*...
%     exp(-i*bb*d)*yy*exp(i*bb*d)*n*y-2*exp(-i*bb*d)*yy^2*exp(i*bb*d)*n^2*y-2*y*...
%     exp(-i*bb*d)*exp(i*b*d)-2*yy*exp(-i*bb*d)*exp(-i*b*d)+2*yy*exp(i*bb*d)*exp(i*b*d)...
%     -2*y*exp(-i*bb*d)*exp(-i*b*d)-2*yy*exp(i*bb*d)*exp(-i*b*d)+2*yy*exp(-i*bb*d)*...
%     exp(i*b*d)+2*y*exp(i*bb*d)*exp(i*b*d)+2*y*exp(i*bb*d)*exp(-i*b*d)+2*yy^2*exp(i*bb*d)...
%     *n*exp(i*b*d)-2*yy^2*exp(i*bb*d)*n*exp(-i*b*d)-yy^2*exp(-i*bb*d)*n*exp(i*b*d)+yy^2*...
%     exp(-i*bb*d)*n*exp(-i*b*d)+2*exp(i*bb*d)*exp(i*b*d)*y^2*n-exp(-i*bb*d)*exp(i*b*d)*y^2*...
%     n-2*exp(i*bb*d)*exp(-i*b*d)*y^2*n+3*exp(-i*bb*d)*exp(-i*b*d)*y^2*n+6*yy^2*exp(i*bb*d)...
%     *n^2*exp(i*b*d)*y+6*yy^2*exp(i*bb*d)*n^2*exp(-i*b*d)*y-3*yy^2*exp(-i*bb*d)*n^2*...
%     exp(i*b*d)*y-3*yy^2*exp(-i*bb*d)*n^2*exp(-i*b*d)*y+8*yy*exp(i*bb*d)*exp(i*b*d)*...
%     y*n+8*yy*exp(i*bb*d)*exp(-i*b*d)*y*n+6*yy*exp(-i*bb*d)*exp(i*b*d)*y*n+8*yy*exp(-i*bb*d)...
%     *exp(-i*b*d)*y*n+6*yy*exp(i*bb*d)*n^2*exp(i*b*d)*y^2+2*yy*exp(-i*bb*d)*n^2*exp(i*b*d)*...
%     y^2-6*yy*exp(i*bb*d)*n^2*exp(-i*b*d)*y^2-8*yy*exp(-i*bb*d)*n^2*exp(-i*b*d)*y^2+...
%     2*exp(-i*bb*d)*exp(i*bb*d)*y^2*n+exp(-i*bb*d)*exp(i*b*d)*y^3*n^2-n^2*exp(-i*bb*d)...
%     *y^3*exp(-i*b*d))*n*E/((yy*exp(-i*bb*d)*n^2*y+yy^2*exp(-i*bb*d)*n^2-2*yy^2*exp(i*bb*d)...
%     *n^2-exp(-i*bb*d)*y*n-4*yy*exp(i*bb*d)*n-3*yy*exp(-i*bb*d)*n+2*exp(-i*bb*d)-2*exp(i*bb*d))...
%     *(n^2*exp(-i*b*d)*y^2-n^2*exp(i*b*d)*y^2-2*exp(i*b*d)*y*n-2*exp(-i*b*d)*y*n+exp(-i*b*d)...
%     -exp(i*b*d)))-1/2*(-6*yy*exp(i*bb*d)*n*exp(i*b*d)+6*yy*exp(i*bb*d)*n*exp(-i*b*d)-6*exp(i*bb*d)*...
%     exp(i*b*d)*y*n-6*exp(i*bb*d)*exp(-i*b*d)*y*n-4*yy*exp(-i*bb*d)*n*exp(i*b*d)+4*yy*exp(-i*bb*d)*n*...
%     exp(-i*b*d)+4*exp(-i*bb*d)*exp(i*b*d)*y*n+8*exp(-i*bb*d)*exp(-i*b*d)*y*n-2*yy^2*exp(i*bb*d)*n^2*...
%     exp(i*b*d)+2*yy^2*exp(i*bb*d)*n^2*exp(-i*b*d)+yy^2*exp(-i*bb*d)*n^2*exp(i*b*d)-yy^2*exp(-i*bb*d)*...
%     n^2*exp(-i*b*d)-2*exp(i*bb*d)*exp(i*b*d)*y^2*n^2-exp(-i*bb*d)*exp(i*b*d)*y^2*n^2+2*exp(i*bb*d)*...
%     exp(-i*b*d)*y^2*n^2-5*exp(-i*bb*d)*exp(-i*b*d)*y^2*n^2+4*exp(-i*bb*d)*exp(i*b*d)-4*exp(i*bb*d)*...
%     exp(i*b*d)+4*exp(i*bb*d)*exp(-i*b*d)-4*exp(-i*bb*d)*exp(-i*b*d)-8*yy*exp(i*bb*d)*n^2*exp(i*b*d)*y-...
%     8*yy*exp(i*bb*d)*n^2*exp(-i*b*d)*y-4*yy*exp(-i*bb*d)*n^2*exp(i*b*d)*y-6*yy*exp(-i*bb*d)*n^2*exp(-i*b*d)*...
%     y-2*yy^2*exp(i*bb*d)*n^3*exp(i*b*d)*y-2*yy^2*exp(i*bb*d)*n^3*exp(-i*b*d)*y+yy^2*exp(-i*bb*d)*n^3*...
%     exp(i*b*d)*y+yy^2*exp(-i*bb*d)*n^3*exp(-i*b*d)*y-2*yy*exp(i*bb*d)*n^3*exp(i*b*d)*y^2+2*yy*exp(i*bb*d)*...
%     n^3*exp(-i*b*d)*y^2+2*yy*exp(-i*bb*d)*n^3*exp(-i*b*d)*y^2+n^3*exp(-i*bb*d)*y^3*exp(-i*b*d)-n^3*exp(-i*bb*d)...
%     *y^3*exp(i*b*d)+2*exp(-i*bb*d)*exp(i*bb*d)*y^2*n^2-2*exp(-i*bb*d)*y*n^2*yy*exp(i*bb*d)+2*exp(-i*bb*d)*...
%     yy*exp(i*bb*d)*n^3*y^2-2*exp(-i*bb*d)*y*n^3*yy^2*exp(i*bb*d))*E/((yy*exp(-i*bb*d)*n^2*y+yy^2*exp(-i*bb*d)...
%     *n^2-2*yy^2*exp(i*bb*d)*n^2-exp(-i*bb*d)*y*n-4*yy*exp(i*bb*d)*n-3*yy*exp(-i*bb*d)*n+2*exp(-i*bb*d)-...
%     2*exp(i*bb*d))*(n^2*exp(-i*b*d)*y^2-n^2*exp(i*b*d)*y^2-2*exp(i*b*d)*y*n-2*exp(-i*b*d)*y*n+exp(-i*b*d)-...
%     exp(i*b*d)))]);
% 
% 
% R2=([-(-2*exp(-i*bb*d)*yy*exp(i*bb*d)*n^2*y^2+2*exp(-i*bb*d)*yy*exp(i*bb*d)*...
%     n*y+2*exp(-i*bb*d)*yy^2*exp(i*bb*d)*n^2*y+2*y*exp(-i*bb*d)*exp(i*b*d)-2*yy*exp(-i*bb*d)*...
%     exp(-i*b*d)+2*yy*exp(i*bb*d)*exp(i*b*d)+2*y*exp(-i*bb*d)*exp(-i*b*d)-2*yy*exp(i*bb*d)*...
%     exp(-i*b*d)+2*yy*exp(-i*bb*d)*exp(i*b*d)-2*y*exp(i*bb*d)*exp(i*b*d)-2*y*exp(i*bb*d)*...
%     exp(-i*b*d)+2*yy^2*exp(i*bb*d)*n*exp(i*b*d)-2*yy^2*exp(i*bb*d)*n*exp(-i*b*d)-yy^2*exp(-i*bb*d)...
%     *n*exp(i*b*d)+yy^2*exp(-i*bb*d)*n*exp(-i*b*d)-2*exp(i*bb*d)*exp(i*b*d)*y^2*n+exp(-i*bb*d)*exp(i*b*d)...
%     *y^2*n+2*exp(i*bb*d)*exp(-i*b*d)*y^2*n-3*exp(-i*bb*d)*exp(-i*b*d)*y^2*n+2*yy^2*exp(i*bb*d)*n^2*...
%     exp(i*b*d)*y+2*yy^2*exp(i*bb*d)*n^2*exp(-i*b*d)*y-yy^2*exp(-i*bb*d)*n^2*exp(i*b*d)*y-yy^2*...
%     exp(-i*bb*d)*n^2*exp(-i*b*d)*y+2*yy*exp(-i*bb*d)*exp(-i*b*d)*y*n-2*yy*exp(i*bb*d)*n^2*exp(i*b*d)...
%     *y^2-2*yy*exp(-i*bb*d)*n^2*exp(i*b*d)*y^2+2*yy*exp(i*bb*d)*n^2*exp(-i*b*d)*y^2-2*exp(-i*bb*d)*...
%     exp(i*bb*d)*y^2*n-exp(-i*bb*d)*exp(i*b*d)*y^3*n^2+n^2*exp(-i*bb*d)*y^3*exp(-i*b*d))*n*i*...
%     E/((yy*exp(-i*bb*d)*n^2*y+yy^2*exp(-i*bb*d)*n^2-2*yy^2*exp(i*bb*d)*n^2-exp(-i*bb*d)*y*n-4*...
%     yy*exp(i*bb*d)*n-3*yy*exp(-i*bb*d)*n+2*exp(-i*bb*d)-2*exp(i*bb*d))*(n^2*exp(-i*b*d)*y^2-...
%     n^2*exp(i*b*d)*y^2-2*exp(i*b*d)*y*n-2*exp(-i*b*d)*y*n+exp(-i*b*d)-exp(i*b*d)))]);
% 
% 
% L1 =([-(yy*exp(-i*bb*d)*n^3*exp(i*b*d)*y^2+exp(-i*bb*d)*yy*exp(i*bb*d)*...
%     n^3*y^2-2*yy^2*exp(i*bb*d)*n^3*exp(i*b*d)*y-exp(-i*bb*d)*y*n^3*yy^2*exp(i*bb*d)+...
%     yy^2*exp(-i*bb*d)*n^3*exp(i*b*d)*y+exp(-i*bb*d)*exp(i*bb*d)*y^2*n^2-exp(-i*bb*d)*...
%     exp(i*b*d)*y^2*n^2-4*yy*exp(i*bb*d)*n^2*exp(i*b*d)*y-2*exp(-i*bb*d)*y*n^2*yy*exp(i*bb*d)-...
%     2*yy*exp(-i*bb*d)*n^2*exp(i*b*d)*y-2*yy^2*exp(i*bb*d)*n^2*exp(i*b*d)+yy^2*exp(-i*bb*d)*...
%     n^2*exp(i*b*d)+exp(-i*bb*d)*yy^2*exp(i*bb*d)*n^2-exp(-i*bb*d)*y*n*exp(i*bb*d)+exp(-i*bb*d)*...
%     exp(i*b*d)*y*n-2*exp(i*bb*d)*exp(i*b*d)*y*n-3*yy*exp(-i*bb*d)*n*exp(i*b*d)+exp(-i*bb*d)*yy*...
%     exp(i*bb*d)*n-4*yy*exp(i*bb*d)*n*exp(i*b*d)+2*exp(-i*bb*d)*exp(i*b*d)-2*exp(i*bb*d)*exp(i*b*d))*...
%     E/(4*yy*exp(i*bb*d)*n*exp(i*b*d)-4*yy*exp(i*bb*d)*n*exp(-i*b*d)+4*exp(i*bb*d)*exp(i*b*d)*y*n+...
%     4*exp(i*bb*d)*exp(-i*b*d)*y*n+3*yy*exp(-i*bb*d)*n*exp(i*b*d)-3*yy*exp(-i*bb*d)*n*exp(-i*b*d)-...
%     3*exp(-i*bb*d)*exp(i*b*d)*y*n-5*exp(-i*bb*d)*exp(-i*b*d)*y*n+2*yy^2*exp(i*bb*d)*n^2*exp(i*b*d)-...
%     2*yy^2*exp(i*bb*d)*n^2*exp(-i*b*d)-yy^2*exp(-i*bb*d)*n^2*exp(i*b*d)+yy^2*exp(-i*bb*d)*n^2*...
%     exp(-i*b*d)+2*exp(i*bb*d)*exp(i*b*d)*y^2*n^2-2*exp(i*bb*d)*exp(-i*b*d)*y^2*n^2+4*exp(-i*bb*d)*...
%     exp(-i*b*d)*y^2*n^2-2*exp(-i*bb*d)*exp(i*b*d)+2*exp(i*bb*d)*exp(i*b*d)-2*exp(i*bb*d)*exp(-i*b*d)+...
%     2*exp(-i*bb*d)*exp(-i*b*d)+8*yy*exp(i*bb*d)*n^2*exp(i*b*d)*y+8*yy*exp(i*bb*d)*n^2*exp(-i*b*d)*y+...
%     5*yy*exp(-i*bb*d)*n^2*exp(i*b*d)*y+7*yy*exp(-i*bb*d)*n^2*exp(-i*b*d)*y+4*yy^2*exp(i*bb*d)*n^3*...
%     exp(i*b*d)*y+4*yy^2*exp(i*bb*d)*n^3*exp(-i*b*d)*y-2*yy^2*exp(-i*bb*d)*n^3*exp(i*b*d)*y-2*yy^2*...
%     exp(-i*bb*d)*n^3*exp(-i*b*d)*y+4*yy*exp(i*bb*d)*n^3*exp(i*b*d)*y^2+yy*exp(-i*bb*d)*n^3*exp(i*b*d)*y^2-...
%     4*yy*exp(i*bb*d)*n^3*exp(-i*b*d)*y^2-5*yy*exp(-i*bb*d)*n^3*exp(-i*b*d)*y^2-n^3*exp(-i*bb*d)*y^3*exp(-i*b*d)+...
%     n^3*exp(-i*bb*d)*y^3*exp(i*b*d)-n^4*yy^2*exp(-i*bb*d)*exp(i*b*d)*y^2+n^4*yy^2*exp(-i*bb*d)*...
%     exp(-i*b*d)*y^2-2*n^4*yy^2*exp(i*bb*d)*exp(-i*b*d)*y^2+2*n^4*yy^2*exp(i*bb*d)*exp(i*b*d)*y^2+...
%     n^4*yy*exp(-i*bb*d)*y^3*exp(-i*b*d)-n^4*yy*exp(-i*bb*d)*y^3*exp(i*b*d))]);
% 
% L2=([-2*(yy*n+1)*exp(i*bb*d)*E/(yy*exp(-i*bb*d)*n^2*y+yy^2*exp(-i*bb*d)*n^2-...
%     2*yy^2*exp(i*bb*d)*n^2-exp(-i*bb*d)*y*n-4*yy*exp(i*bb*d)*n-3*yy*exp(-i*bb*d)*n+...
%     2*exp(-i*bb*d)-2*exp(i*bb*d))]);
% 
% 
% G1=([-(yy*exp(-i*bb*d)*n^3*exp(-i*b*d)*y^2+exp(-i*bb*d)*yy*exp(i*bb*d)*n^3*y^2+...
%     yy^2*exp(-i*bb*d)*n^3*exp(-i*b*d)*y-2*yy^2*exp(i*bb*d)*n^3*exp(-i*b*d)*y-exp(-i*bb*d)*y*...
%     n^3*yy^2*exp(i*bb*d)-exp(-i*bb*d)*exp(-i*b*d)*y^2*n^2+exp(-i*bb*d)*exp(i*bb*d)*y^2*n^2-4*...
%     yy*exp(i*bb*d)*n^2*exp(-i*b*d)*y-4*yy*exp(-i*bb*d)*n^2*exp(-i*b*d)*y-yy^2*exp(-i*bb*d)*n^2...
%     *exp(-i*b*d)+2*yy^2*exp(i*bb*d)*n^2*exp(-i*b*d)-exp(-i*bb*d)*yy^2*exp(i*bb*d)*n^2+3*exp(-i*bb*d)...
%     *exp(-i*b*d)*y*n-2*exp(i*bb*d)*exp(-i*b*d)*y*n+exp(-i*bb*d)*y*n*exp(i*bb*d)+4*yy*exp(i*bb*d)*n*...
%     exp(-i*b*d)+3*yy*exp(-i*bb*d)*n*exp(-i*b*d)-exp(-i*bb*d)*yy*exp(i*bb*d)*n-2*exp(-i*bb*d)*exp(-i*b*d)+...
%     2*exp(i*bb*d)*exp(-i*b*d))*E/(4*yy*exp(i*bb*d)*n*exp(i*b*d)-4*yy*exp(i*bb*d)*n*exp(-i*b*d)+4*...
%     exp(i*bb*d)*exp(i*b*d)*y*n+4*exp(i*bb*d)*exp(-i*b*d)*y*n+3*yy*exp(-i*bb*d)*n*exp(i*b*d)-3*yy*...
%     exp(-i*bb*d)*n*exp(-i*b*d)-3*exp(-i*bb*d)*exp(i*b*d)*y*n-5*exp(-i*bb*d)*exp(-i*b*d)*y*n+2*yy^2*...
%     exp(i*bb*d)*n^2*exp(i*b*d)-2*yy^2*exp(i*bb*d)*n^2*exp(-i*b*d)-yy^2*exp(-i*bb*d)*n^2*exp(i*b*d)+...
%     yy^2*exp(-i*bb*d)*n^2*exp(-i*b*d)+2*exp(i*bb*d)*exp(i*b*d)*y^2*n^2-2*exp(i*bb*d)*exp(-i*b*d)*y^2*n^2+...
%     4*exp(-i*bb*d)*exp(-i*b*d)*y^2*n^2-2*exp(-i*bb*d)*exp(i*b*d)+2*exp(i*bb*d)*exp(i*b*d)-2*exp(i*bb*d)*...
%     exp(-i*b*d)+2*exp(-i*bb*d)*exp(-i*b*d)+8*yy*exp(i*bb*d)*n^2*exp(i*b*d)*y+8*yy*exp(i*bb*d)*n^2*exp(-i*b*d)...
%     *y+5*yy*exp(-i*bb*d)*n^2*exp(i*b*d)*y+7*yy*exp(-i*bb*d)*n^2*exp(-i*b*d)*y+4*yy^2*exp(i*bb*d)*n^3*...
%     exp(i*b*d)*y+4*yy^2*exp(i*bb*d)*n^3*exp(-i*b*d)*y-2*yy^2*exp(-i*bb*d)*n^3*exp(i*b*d)*y-2*yy^2*...
%     exp(-i*bb*d)*n^3*exp(-i*b*d)*y+4*yy*exp(i*bb*d)*n^3*exp(i*b*d)*y^2+yy*exp(-i*bb*d)*n^3*exp(i*b*d)*y^2-...
%     4*yy*exp(i*bb*d)*n^3*exp(-i*b*d)*y^2-5*yy*exp(-i*bb*d)*n^3*exp(-i*b*d)*y^2-n^3*exp(-i*bb*d)*y^3*...
%     exp(-i*b*d)+n^3*exp(-i*bb*d)*y^3*exp(i*b*d)-n^4*yy^2*exp(-i*bb*d)*exp(i*b*d)*y^2+n^4*yy^2*exp(-i*bb*d)*...
%     exp(-i*b*d)*y^2-2*n^4*yy^2*exp(i*bb*d)*exp(-i*b*d)*y^2+2*n^4*yy^2*exp(i*bb*d)*exp(i*b*d)*y^2+n^4*yy*...
%     exp(-i*bb*d)*y^3*exp(-i*b*d)-n^4*yy*exp(-i*bb*d)*y^3*exp(i*b*d))]);
% 
% G2=([-exp(-i*bb*d)*(yy*n+y*n-2)*E/(yy*exp(-i*bb*d)*n^2*y+yy^2*exp(-i*bb*d)*n^2-...
%     2*yy^2*exp(i*bb*d)*n^2-exp(-i*bb*d)*y*n-4*yy*exp(i*bb*d)*n-3*yy*exp(-i*bb*d)*n+...
%     2*exp(-i*bb*d)-2*exp(i*bb*d))]);
E=1;
T1= -((n^2*exp(-i*bb*d)*y^3*exp(-i*b*d)*exp(i*bb*d)-n^2*exp(-i*bb*d)*y^3*exp(i*b*d)*...
    exp(i*bb*d)+4*n^2*yy*exp(-i*bb*d)*y^2*exp(-i*b*d)*exp(i*bb*d)+2*n^2*yy*exp(-i*bb*d)*y^2*exp(-i*b*d)*...
    exp(i*b*d)-2*n^2*yy*exp(-i*bb*d)*y^2*exp(i*b*d)*exp(i*bb*d)-yy^2*exp(i*bb*d)*exp(-i*bb*d)*n^2*...
    exp(-i*b*d)*y+2*n^2*yy^2*y*exp(-i*b*d)*exp(i*b*d)*exp(-i*bb*d)-4*n^2*yy^2*y*exp(-i*b*d)*exp(i*b*d)*...
    exp(i*bb*d)-yy^2*exp(i*bb*d)*exp(i*b*d)*exp(-i*bb*d)*n^2*y-y^2*exp(-i*bb*d)*exp(i*bb*d)*exp(-i*b*d)*n-...
    2*n*exp(-i*bb*d)*y^2*exp(-i*b*d)*exp(i*b*d)-y^2*exp(-i*bb*d)*exp(i*b*d)*exp(i*bb*d)*n-6*y*exp(-i*b*d)*yy*n...
    *exp(i*b*d)*exp(-i*bb*d)-8*y*n*exp(-i*b*d)*yy*exp(i*bb*d)*exp(-i*bb*d)-8*y*exp(-i*b*d)*yy*n*exp(i*b*d)*...
    exp(i*bb*d)-6*yy*exp(-i*bb*d)*exp(i*b*d)*y*n*exp(i*bb*d)+n*yy^2*exp(-i*b*d)*exp(i*bb*d)*exp(-i*bb*d)-...
    n*exp(i*b*d)*yy^2*exp(i*bb*d)*exp(-i*bb*d)+4*y*exp(-i*b*d)*exp(i*b*d)*exp(-i*bb*d)-4*y*exp(-i*b*d)*...
    exp(i*b*d)*exp(i*bb*d)+4*exp(-i*b*d)*yy*exp(i*bb*d)*exp(-i*bb*d)-4*exp(i*b*d)*yy*exp(i*bb*d)*...
    exp(-i*bb*d))*n*E/(exp(-i*k*d)*(4*yy*exp(i*bb*d)*n*exp(i*b*d)-4*yy*exp(i*bb*d)*n*exp(-i*b*d)+...
    4*exp(i*bb*d)*exp(i*b*d)*y*n+4*exp(i*bb*d)*exp(-i*b*d)*y*n+3*yy*exp(-i*bb*d)*n*exp(i*b*d)-3*yy*...
    exp(-i*bb*d)*n*exp(-i*b*d)-3*exp(-i*bb*d)*exp(i*b*d)*y*n-5*exp(-i*bb*d)*exp(-i*b*d)*y*n+2*yy^2*...
    exp(i*bb*d)*n^2*exp(i*b*d)-2*yy^2*exp(i*bb*d)*n^2*exp(-i*b*d)-yy^2*exp(-i*bb*d)*n^2*exp(i*b*d)+...
    yy^2*exp(-i*bb*d)*n^2*exp(-i*b*d)+2*exp(i*bb*d)*exp(i*b*d)*y^2*n^2-2*exp(i*bb*d)*exp(-i*b*d)*y^2*n^2+...
    4*exp(-i*bb*d)*exp(-i*b*d)*y^2*n^2-2*exp(-i*bb*d)*exp(i*b*d)+2*exp(i*bb*d)*exp(i*b*d)-2*exp(i*bb*d)*...
    exp(-i*b*d)+2*exp(-i*bb*d)*exp(-i*b*d)+8*yy*exp(i*bb*d)*n^2*exp(i*b*d)*y+8*yy*exp(i*bb*d)*n^2*...
    exp(-i*b*d)*y+5*yy*exp(-i*bb*d)*n^2*exp(i*b*d)*y+7*yy*exp(-i*bb*d)*n^2*exp(-i*b*d)*y+4*yy^2*...
    exp(i*bb*d)*n^3*exp(i*b*d)*y+4*yy^2*exp(i*bb*d)*n^3*exp(-i*b*d)*y-2*yy^2*exp(-i*bb*d)*n^3*...
    exp(i*b*d)*y-2*yy^2*exp(-i*bb*d)*n^3*exp(-i*b*d)*y+4*yy*exp(i*bb*d)*n^3*exp(i*b*d)*y^2+yy*...
    exp(-i*bb*d)*n^3*exp(i*b*d)*y^2-4*yy*exp(i*bb*d)*n^3*exp(-i*b*d)*y^2-5*yy*exp(-i*bb*d)*n^3*...
    exp(-i*b*d)*y^2-n^3*exp(-i*bb*d)*y^3*exp(-i*b*d)+n^3*exp(-i*bb*d)*y^3*exp(i*b*d)-n^4*yy^2*...
    exp(-i*bb*d)*exp(i*b*d)*y^2+n^4*yy^2*exp(-i*bb*d)*exp(-i*b*d)*y^2-2*n^4*yy^2*exp(i*bb*d)*exp(-i*b*d)*y^2+...
    2*n^4*yy^2*exp(i*bb*d)*exp(i*b*d)*y^2+n^4*yy*exp(-i*bb*d)*y^3*exp(-i*b*d)-n^4*yy*exp(-i*bb*d)*y^3*exp(i*b*d))));


T2=[-i*(-2*n^2*yy^2*y*exp(-i*b*d)*exp(i*b*d)*exp(-i*bb*d)+yy^2*exp(i*bb*d)*exp(-i*bb*d)*...
    n^2*exp(-i*b*d)*y+yy^2*exp(i*bb*d)*exp(i*b*d)*exp(-i*bb*d)*n^2*y+4*n^2*yy^2*y*exp(-i*b*d)*exp(i*b*d)*...
    exp(i*bb*d)+2*n^2*yy*exp(-i*bb*d)*y^2*exp(-i*b*d)*exp(i*bb*d)-2*n^2*yy*exp(-i*bb*d)*y^2*exp(-i*b*d)*...
    exp(i*b*d)-4*n^2*yy*exp(-i*bb*d)*y^2*exp(i*b*d)*exp(i*bb*d)+n^2*exp(-i*bb*d)*y^3*exp(-i*b*d)*exp(i*bb*d)-...
    n^2*exp(-i*bb*d)*y^3*exp(i*b*d)*exp(i*bb*d)+n*exp(i*b*d)*yy^2*exp(i*bb*d)*exp(-i*bb*d)-n*yy^2*exp(-i*b*d)*...
    exp(i*bb*d)*exp(-i*bb*d)-6*yy*exp(-i*bb*d)*exp(i*b*d)*y*n*exp(i*bb*d)+6*y*exp(-i*b*d)*yy*n*exp(i*b*d)*...
    exp(-i*bb*d)-4*y*n*exp(-i*b*d)*yy*exp(i*bb*d)*exp(-i*bb*d)+8*y*exp(-i*b*d)*yy*n*exp(i*b*d)*exp(i*bb*d)-...
    3*y^2*exp(-i*bb*d)*exp(i*bb*d)*exp(-i*b*d)*n+2*n*exp(-i*bb*d)*y^2*exp(-i*b*d)*exp(i*b*d)-3*y^2*exp(-i*bb*d)*...
    exp(i*b*d)*exp(i*bb*d)*n-2*exp(i*b*d)*yy*exp(i*bb*d)*exp(-i*bb*d)+2*exp(-i*b*d)*yy*exp(i*bb*d)*...
    exp(-i*bb*d)-4*y*exp(-i*b*d)*exp(i*b*d)*exp(-i*bb*d)+2*exp(i*bb*d)*y*exp(-i*bb*d)*exp(-i*b*d)-2*exp(i*bb*d)*...
    exp(i*b*d)*y*exp(-i*bb*d)+4*y*exp(-i*b*d)*exp(i*b*d)*exp(i*bb*d))*n*E/(exp(-i*k*d)*(4*yy*exp(i*bb*d)*...
    n*exp(i*b*d)-4*yy*exp(i*bb*d)*n*exp(-i*b*d)+4*exp(i*bb*d)*exp(i*b*d)*y*n+4*exp(i*bb*d)*exp(-i*b*d)*y*n+...
    3*yy*exp(-i*bb*d)*n*exp(i*b*d)-3*yy*exp(-i*bb*d)*n*exp(-i*b*d)-3*exp(-i*bb*d)*exp(i*b*d)*y*n-5*exp(-i*bb*d)*...
    exp(-i*b*d)*y*n+2*yy^2*exp(i*bb*d)*n^2*exp(i*b*d)-2*yy^2*exp(i*bb*d)*n^2*exp(-i*b*d)-yy^2*exp(-i*bb*d)*...
    n^2*exp(i*b*d)+yy^2*exp(-i*bb*d)*n^2*exp(-i*b*d)+2*exp(i*bb*d)*exp(i*b*d)*y^2*n^2-2*exp(i*bb*d)*exp(-i*b*d)*...
    y^2*n^2+4*exp(-i*bb*d)*exp(-i*b*d)*y^2*n^2-2*exp(-i*bb*d)*exp(i*b*d)+2*exp(i*bb*d)*exp(i*b*d)-2*exp(i*bb*d)*...
    exp(-i*b*d)+2*exp(-i*bb*d)*exp(-i*b*d)+8*yy*exp(i*bb*d)*n^2*exp(i*b*d)*y+8*yy*exp(i*bb*d)*n^2*exp(-i*b*d)*y+...
    5*yy*exp(-i*bb*d)*n^2*exp(i*b*d)*y+7*yy*exp(-i*bb*d)*n^2*exp(-i*b*d)*y+4*yy^2*exp(i*bb*d)*n^3*exp(i*b*d)*y+...
    4*yy^2*exp(i*bb*d)*n^3*exp(-i*b*d)*y-2*yy^2*exp(-i*bb*d)*n^3*exp(i*b*d)*y-2*yy^2*exp(-i*bb*d)*n^3*...
    exp(-i*b*d)*y+4*yy*exp(i*bb*d)*n^3*exp(i*b*d)*y^2+yy*exp(-i*bb*d)*n^3*exp(i*b*d)*y^2-4*yy*exp(i*bb*d)*...
    n^3*exp(-i*b*d)*y^2-5*yy*exp(-i*bb*d)*n^3*exp(-i*b*d)*y^2-n^3*exp(-i*bb*d)*y^3*exp(-i*b*d)+n^3*...
    exp(-i*bb*d)*y^3*exp(i*b*d)-n^4*yy^2*exp(-i*bb*d)*exp(i*b*d)*y^2+n^4*yy^2*exp(-i*bb*d)*exp(-i*b*d)*...
    y^2-2*n^4*yy^2*exp(i*bb*d)*exp(-i*b*d)*y^2+2*n^4*yy^2*exp(i*bb*d)*exp(i*b*d)*y^2+n^4*yy*exp(-i*bb*d)*...
    y^3*exp(-i*b*d)-n^4*yy*exp(-i*bb*d)*y^3*exp(i*b*d)))];
figure(2);
for t=1:45
    compass(abs(T1+T2));
   
    hold on;
    Ex = (T1)*exp(-i*k*d)*exp(i*o*t/(scale));
    Ey = (T2)*exp(-i*k*d)*exp(i*o*t/(scale));
    compass(real(Ex),real(Ey));   
    M(t) = getframe;
    hold off;
    
end

 exp(-i*k0*d);