 // EXAMPLE INPUT-01

 // HOW TO INPUT SOME SIMPLE TYPES

 #include <header.h>

 int main()
 {
    int number ;
    cout << "Enter a number: " ;
    cin >> number ;
    cout << "You entered: "
         << number
         << '\n' ;

    char ch ;
    cout << "Enter a character: " ;
    cin >> ch ;
    cout << "You entered: "
         << ch
         << '\n' ;

    float fl ;
    cout << "Enter a float: " ;
    cin >> fl ;
    cout << "You entered: "
         << fl
         << '\n' ;

    return 0 ;
 }
