# Project: Projekt1
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = adt/doublematrix/add.o adt/doublematrix/free_doublematrix.o adt/doublematrix/mul.o adt/doublematrix/new_doublematrix.o adt/doublematrix/print_doublematrix.o adt/doublematrix/read_doublematrix.o adt/doublematrix/sub.o a2.o $(RES)
LINKOBJ  = adt/doublematrix/add.o adt/doublematrix/free_doublematrix.o adt/doublematrix/mul.o adt/doublematrix/new_doublematrix.o adt/doublematrix/print_doublematrix.o adt/doublematrix/read_doublematrix.o adt/doublematrix/sub.o a2.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" -mwindows  
INCS =  -I"C:/Dev-Cpp/include" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include" 
BIN  = Projekt1.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before Projekt1.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "Projekt1.exe" $(LIBS)

adt/doublematrix/add.o: adt/doublematrix/add.c
	$(CC) -c adt/doublematrix/add.c -o adt/doublematrix/add.o $(CFLAGS)

adt/doublematrix/free_doublematrix.o: adt/doublematrix/free_doublematrix.c
	$(CC) -c adt/doublematrix/free_doublematrix.c -o adt/doublematrix/free_doublematrix.o $(CFLAGS)

adt/doublematrix/mul.o: adt/doublematrix/mul.c
	$(CC) -c adt/doublematrix/mul.c -o adt/doublematrix/mul.o $(CFLAGS)

adt/doublematrix/new_doublematrix.o: adt/doublematrix/new_doublematrix.c
	$(CC) -c adt/doublematrix/new_doublematrix.c -o adt/doublematrix/new_doublematrix.o $(CFLAGS)

adt/doublematrix/print_doublematrix.o: adt/doublematrix/print_doublematrix.c
	$(CC) -c adt/doublematrix/print_doublematrix.c -o adt/doublematrix/print_doublematrix.o $(CFLAGS)

adt/doublematrix/read_doublematrix.o: adt/doublematrix/read_doublematrix.c
	$(CC) -c adt/doublematrix/read_doublematrix.c -o adt/doublematrix/read_doublematrix.o $(CFLAGS)

adt/doublematrix/sub.o: adt/doublematrix/sub.c
	$(CC) -c adt/doublematrix/sub.c -o adt/doublematrix/sub.o $(CFLAGS)

a2.o: a2.c
	$(CC) -c a2.c -o a2.o $(CFLAGS)
