dirlist:
	#cd doublematrix; make; cd ..
	cd list; make; cd ..
	cd error; make; cd ..

clean:
	rm -f libadt.a
	#cd doublematrix; make clean; cd ..
	cd error; make clean; cd ..
	cd list; make clean; cd ..
